connections {
    example {
        version = 1
        local_addrs = %any
        remote_addrs = vpn.example.com
        encap = yes
        keyingtries = 0
        rekey_time = 0
        proposals = aes256-sha256-modp2048,aes128-sha1-modp1024,default

        local {
            auth = psk
        }
        remote {
            auth = psk
        }

        children {
            example {
                mode = transport
                local_ts = dynamic[udp/l2tp]
                remote_ts = dynamic[udp/l2tp]
                esp_proposals = aes256-sha256,aes128-sha1,default
                start_action = none
                dpd_action = clear
            }
        }
    }
}

secrets {
    ike-example {
        id = %any
        secret = "replace-with-preshared-key"
    }
}
