[global]
access control = no
port = 1701

[lac example]
lns = vpn.example.com
require chap = yes
refuse pap = yes
require authentication = no
name = replace-with-ppp-username
pppoptfile = /etc/ppp/peers/example
length bit = yes
redial = yes
redial timeout = 10
max redials = 5
